### ISSUE TITLE
Display without month/day text

### ISSUE THREAD

**Issue by stvhwrd** [2016rshah/githubchart-api#13]
Is it possible to display the contributions chart without text?

Like this:

![image](https://user-images.githubusercontent.com/4117011/35419364-61bea738-01ec-11e8-94d8-9e14040459b8.png)

Thanks for hosting this!  I love it.

**Comment by 2016rshah** [comment]
So the actual chart SVG's are generated from [this awesome ruby gem](https://github.com/akerl/githubchart). Since this is a rendering question, you would have to go over to that repo and try to merge something in that renders it without the text. 

After that gem generates the image like your example, I would be happy to merge something in for a new text-less route! Until then I'm going to close this comment, but feel free to open it back up if there are any updates.
