### ISSUE TITLE
Ability to set base color

### ISSUE THREAD

**Issue by SamirMokiem** [2016rshah/githubchart-api#14]
Hi!

Nice program you made! I want to use it on my personal site but i have a problem. Its a dark themed website and with that, the colors doesnt work. I already set the gradient color to a blue color but i also want to set te base color to a dark gray color so it matches my site. How am i able to do this?

img:
https://image.ibb.co/mmnWay/gherror.png

**Comment by SamirMokiem** [comment]
Now im using the 
> filter: invert(100%);
in css and i am setting the color to the inverted color (6c3813 to BE7C3B)
and now i get this:

https://preview.ibb.co/g9SmyT/Knipsel.png

it kinda works but im more pleased to set the base color :)

**Comment by 2016rshah** [comment]
So the actual chart SVG's are generated from [this awesome ruby gem](https://github.com/akerl/githubchart). Since this is a rendering question, you would have to go over to that repo and try to merge something in that renders it with a different base color.

After that gem generates the image you're looking for, I would be happy to merge something in for a new route with base-colors! Until then I'm going to close this comment, but feel free to open it back up if there are any updates :)
