### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by brandonbyr4** [2016rshah/githubchart-api#29]
Does not work any more

**Comment by linuxdeepin007** [comment]
It seems to be failed

**Comment by isinaltinkaya** [comment]
Does not work for me, too

**Comment by carlalexander** [comment]
It's because of #28. Heroku shut down its free tier 2 days ago.

**Comment by linuxdeepin007** [comment]
> 

but can we use the author' github codes to rebuild one

**Comment by brandonbyr4** [comment]
@linuxdeepin007 That is my idea as well

**Comment by umazhar** [comment]
whos gonna do it

**Comment by stbaker517** [comment]
My project has made on this api but it's broken 

So sad..

**Comment by stbaker517** [comment]
@2016rshah

**Comment by Neilblaze** [comment]
Same for me too folks! I guess, since he's still in academia, he can apply to [this](https://www.heroku.com/github-students) to avoid unnecessary fee charges.

^^ @2016rshah

**Comment by linuxdeepin007** [comment]
https://github.com/Ashutosh00710/github-readme-activity-graph/

anyone can use this github？

**Comment by linuxdeepin007** [comment]
@ThePlugJumbo  after a whole day's searching, It seems that i find a alternative way to display the contribution of github.
first, you can see the page of my blog. https://linuxdeepin007.github.io/code.github.io/about/
second, you can see the repo  ：https://github.com/Ashutosh00710/github-readme-activity-graph/

**Comment by 2016rshah** [comment]
Yep, y'all are correct this stopped working because Heroku stopped providing free hosting, as mentioned in #28. 

If anybody is willing to start paying for hosting, that would be ideal! Just push the project onto Heroku, it should be pretty straightforward, let me know if you need help. 

I've also been pursuing the student developer pack option that @Neilblaze mentioned, but it takes 24 hours to be verified. It's also finals season, so this project is not really my priority. And even if this option works, the credits are only valid for twelve months so we will have the same problem next year.

**Comment by Neilblaze** [comment]
Thanks for the mention @2016rshah 🙌 
I think all it requires is a valid school email, so technically you can easily renew it till it expires on your end. Also, I'm planning to build something similar which can run on Vercel's serverless functions, so that it can keep running for free, forever! :)

**Comment by brandonbyr4** [comment]
@Neilblaze That is my idea as well.  Rebuild this with next.js and deploy to vercel for free.  Let me know if you create that repo and I would contribute 👍

**Comment by 2016rshah** [comment]
I used the github student developer pack to get hosting credits, so this should be fixed now. See y'all next year when the credits run out!
