### ISSUE TITLE
Text colour options.

### ISSUE THREAD

**Issue by JamesNuttall** [2016rshah/githubchart-api#9]
Would be useful to have the ability to adjust the text colour (on the month names etc).

**Comment by 2016rshah** [comment]
Hmm since that's more related to the actual rendering of the chart than the API part you might want to open up an issue on [this project](https://github.com/akerl/githubchart) (which githubchart-api uses internally). If you open an issue there definitely tag me in it so I can follow along!

If the feature gets supported there I would be happy to merge a PR that adapts the API to expose an endpoint for it (until then I'm going to close this issue)
